runtime: nodejs20

env_variables:
  NODE_ENV: production
  NEXTAUTH_URL: https://mradvanceaihub.uc.r.appspot.com
  NEXTAUTH_SECRET: AjIu9K3ZISNDrODK5gr3NM3zqKdN1OpyEFn6jKen3po=
  DATABASE_URL: mongodb+srv://zy:12345678%40Y@chathistory.mongocluster.cosmos.azure.com/mradvance?retryWrites=true&w=majority&appName=chathistory
  
  # Backend Connection (ngrok URL for local development)
  NEXT_PUBLIC_BACKEND_URL: https://5381-216-165-95-189.ngrok-free.app
  
  # Email Configuration (Gmail SMTP)
  SMTP_HOST: smtp.gmail.com
  SMTP_PORT: 587
  SMTP_USER: kerryyang676@gmail.com
  SMTP_PASS: xzta xosa vmrp yszt
  EMAIL_FROM: "Mr. Advance AI Hub <kerryyang676@gmail.com>"

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

# Simplified handlers for Next.js
handlers:
- url: /.*
  script: auto
  secure: always 